### PR TITLE
Update to kernel 5.19

### PR DESCRIPTION
**Pull request by ikegami-t**
Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>

### CODE REVIEW

**Comment by ikegami-t** [comment]
Note: The error was caunsed by the changes below I think.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7b0a0e3c3a882
By the way it seems that it is better to be ported the driver into kernel as mainted on the kernel for the driver related changes.

**Comment by morrownr** [comment]
I will review your PR and let you know.

>  it seems that it is better to be ported the driver into kernel

Cannot do that. These Realtek out-of-kernel drivers are not Linux standards compliant and it would take a massive effort to change them into a standards compliant driver that could be in the kernel. Only Realtek can do that.

I invited you to the Main Menu as it contains links to a lot of information about using usb wifi adapters on Linux. Let me recommend it again. To avoid dealing with Realtek driver issues, you can get adapters that use in-kernel standards compliant driver. Item 2 on the Main Menu provides a very long list of adapters that use in-kernel drivers... including the new tri band WiFi 6 adapters.

Regards

**Comment by morrownr** [comment]
@ikegami-t 

I am going to put this PR on hold and keep an eye out for issues. I am not seeing any problems and this is a heavily used repo. If you find any additional info, please report.

Regards,

Nick

**Comment by ikegami-t** [comment]
> @ikegami-t
> 
> I am going to put this PR on hold and keep an eye out for issues. I am not seeing any problems and this is a heavily used repo. If you find any additional info, please report.

Thanks for your reviewing.
Sorry I have just pushed the additional patch to fix the changes to enable on kernel 5.19.2 and 6.0.0 since the changes are required actually for 5.9.2 and 6.0.0 but not for 5.9(.0).
Also I have retested the changes as the driver works correctly with the kernel versions below on Ubuntu 22.04.1.
  1. 5.15.0-46-generic
  2. 5.19.0
  3. 5.19.1
  4. 5.19.2
  5. 5.19.0+: d4252071b97d ("add barriers to buffer_uptodate and set_buffer_uptodate")
  6. 6.0.0-rc1
  7. 6.0.0-rc1+: 274a2eebf80c ("Merge tag 'for_linus' of git://git.kernel.org/pub/scm/linux/kernel/git/mst/vhost")

Regards,
Ikegami

> 
> Regards,
> 
> Nick

**Comment by morrownr** [comment]
@ikegami-t 

> the changes are required actually for 5.19.2 and 6.0.0 but not for 5.19(.0).

I see. I was testing 5.19.1.

> Also I have retested the changes as the driver works correctly with the kernel versions below on Ubuntu 22.04.1.

Good.

Give me a chance to reconfigure with kernel 5.19.2 so I can test. I will also need to run tests back to kernel 4.19. Remember, I have to consider the entire world and any kernel that is still officially supported. Will let you know.

**Comment by morrownr** [comment]
@ikegami-t 

I am able to duplicate the problem with kernel 5.19.2. Thanks for being persistent about this issue and for developing a solution. It is appreciated.

I will start the process of including your fix. It caught me off guard that there is something in a point release that is causing this much problem. 

Nick

**Comment by ikegami-t** [comment]
Thanks for the merge by commit db48b7e.

**Comment by morrownr** [comment]
The thanks goes to you! You are welcome to submit PRs anytime.

I actually did not directly use this PR as you can see. I  applied the patch to test separately and then used meld to feed the patch back into the main repo and into the other 4 rtw repos. That easier and faster given my setup and the need to get the patch in place in so many repos.

Nick

**Pull request closed without merging**
