### PR TITLE
remove bc as a dependency

### PR DESCRIPTION
**Pull request by tleydxdy**

### CODE REVIEW

**Comment by morrownr** [comment]
Hi @tleydxdy 

> remove bc as a dependency

That part of your PR is something we need to discuss. I agree with you if all users were installing on fairly recent distros but some users are not. I post support back to kernel 4.19 and if we look at some distros that are that old but still supported, bc needs to be there. The good news is that the package manager just smiles and says already here and presses on if it is already installed.

The rest of the PR is good if you want to resubmit without the bc stuff.

Thanks,

Nick

**Comment by tleydxdy** [comment]
the usage of sort and printf here should all be posix compliant afaik, so even really old distro should support them.

**Comment by morrownr** [comment]
> the usage of sort and printf here should all be posix compliant afaik, so even really old distro should support them.

That is not the issue. The issue is deleting bc. If bc is not installed, it can be a messy compile. 

I appreciate the help and you are certainly welcome to continue.

**Comment by morrownr** [comment]
> there's other places that depends on bc other than in the makefile?

Not that I am aware of.

**Comment by tleydxdy** [comment]
so since I replaced the only usage of bc, it should be fine to remove right?

**Comment by morrownr** [comment]
Let's go ahead and give it a try. Thanks.

**Pull request merged**
